name: campus_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.16.3+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # ↓↓↓ ここから追加した機能 ↓↓↓
  # 日本語化に必要な機能
  flutter_localizations:
    sdk: flutter
  
  # 日付フォーマットなどの機能
  intl: 0.20.2
  
  # データ保存機能
  shared_preferences: ^2.3.2
  # ↑↑↑ ここまで追加 ↑↑↑

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true